import os
import re
import requests
from typing import Dict, List, Any, Tuple
from flask import Blueprint, request, jsonify
from db import db
from sqlalchemy.sql import text

# Initialize Blueprint for AI Chat endpoints
ai_chat_blueprint = Blueprint("ai_chat", __name__)

# Configurable constants for Ollama LLM endpoint
OLLAMA_ENDPOINT: str = os.getenv("OLLAMA_ENDPOINT", "http://147.93.18.205:11434/api/generate")
OLLAMA_MODEL: str = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:1.5b")
REQUEST_TIMEOUT_SECONDS: int = 90
DEFAULT_SQL_LIMIT: int = 50


# Database Schema context provided to the LLM for Text-to-SQL generation
DB_SCHEMA: str = """
-- MySQL Database Schema Context for Space Luggage ERP

CREATE TABLE production_batch (
    id INT PRIMARY KEY AUTO_INCREMENT,
    production_code VARCHAR(50),
    product_id INT,
    planned_qty DECIMAL(18,4),
    completed_qty DECIMAL(18,4),
    client_id INT,
    floor INT,
    expected_completion_date DATETIME,
    batch_status VARCHAR(30), -- e.g. 'pending', 'in_progress', 'completed'
    priority INT
);

CREATE TABLE finished_goods (
    id INT PRIMARY KEY AUTO_INCREMENT,
    product_name VARCHAR(255),
    sku_code VARCHAR(100),
    brand_id INT,
    product_category_id INT,
    stock_qty DECIMAL(18,4),
    min_level DECIMAL(18,4),
    max_level DECIMAL(18,4),
    unit_price DECIMAL(18,2),
    total_value DECIMAL(18,2),
    goods_status VARCHAR(30) -- e.g. 'in-stock'
);

CREATE TABLE products_sku (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sku_code VARCHAR(100),
    product_name VARCHAR(255),
    product_category_id INT,
    brand_id INT,
    unit_price DECIMAL(18,2)
);

CREATE TABLE raw_materials (
    id INT PRIMARY KEY AUTO_INCREMENT,
    material_code VARCHAR(50),
    material_name VARCHAR(255),
    raw_material_category_id INT,
    stock_qty DECIMAL(10,2),
    unit_of_measure VARCHAR(50),
    unit_cost DECIMAL(12,2),
    total_value DECIMAL(14,2),
    stock_status VARCHAR(50)
);

CREATE TABLE vendors (
    id INT PRIMARY KEY AUTO_INCREMENT,
    vendor_name VARCHAR(255),
    contact_person VARCHAR(255),
    phone VARCHAR(30),
    email VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    payment_terms VARCHAR(100)
);

CREATE TABLE employees (
    id INT PRIMARY KEY AUTO_INCREMENT,
    employee_code VARCHAR(50),
    name VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(255),
    department_id INT,
    role VARCHAR(100),
    emp_status VARCHAR(30)
);

CREATE TABLE orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    order_code VARCHAR(50),
    client_id INT,
    product_sku_id INT,
    quantity DECIMAL(10,2),
    order_status VARCHAR(50), -- e.g. 'pending', 'completed'
    expected_delivery_date DATE,
    created_at TIMESTAMP
);

CREATE TABLE clients (
    id INT PRIMARY KEY AUTO_INCREMENT,
    company_name VARCHAR(255),
    contact_person VARCHAR(255),
    email VARCHAR(100),
    phone VARCHAR(50)
);

CREATE TABLE purchase_orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    po_number VARCHAR(100),
    vendor_id INT,
    total_amount DECIMAL(10,2),
    status VARCHAR(50),
    po_date DATETIME
);
"""

# System prompt forcing Ollama to return ONLY executable MySQL SQL queries
SYSTEM_PROMPT_SQL_GEN: str = f"""
You are an expert MySQL Data Engineer.
Given the database schema below, your task is to convert the user's natural language question into a valid, executable MySQL SELECT query.

Database Schema:
{DB_SCHEMA}

CRITICAL RULES:
1. Output ONLY the raw SQL query.
2. Do NOT wrap the query in markdown code blocks like ```sql or ```.
3. Do NOT provide explanations, commentary, or text before/after the SQL query.
4. Only generate read-only SELECT queries.
5. Ensure all table aliases match the table in the FROM clause (e.g. `SELECT r.stock_qty FROM raw_materials r` or `SELECT f.stock_qty FROM finished_goods f`). NEVER use undefined aliases like `p.` on `raw_materials`.
6. For conversational/follow-up questions like "why everything is 0" or general questions, query relevant inventory summary totals (e.g., `SELECT 'finished_goods' AS item_type, COUNT(*) AS count, SUM(stock_qty) AS total_qty FROM finished_goods UNION ALL SELECT 'raw_materials', COUNT(*), SUM(stock_qty) FROM raw_materials`).
"""



def call_ollama(prompt: str, system_prompt: str = "", timeout_seconds: int = REQUEST_TIMEOUT_SECONDS) -> str:
    """
    Sends a request to the remote Ollama LLM endpoint and returns the text response.

    Args:
        prompt (str): The user or structured prompt.
        system_prompt (str): Optional system prompt instructions.
        timeout_seconds (int): Custom timeout limit in seconds.

    Returns:
        str: Raw text generated by the Ollama model.

    Raises:
        Exception: If the HTTP request fails or times out.
    """
    payload: Dict[str, Any] = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False
    }
    if system_prompt:
        payload["system"] = system_prompt

    response = requests.post(
        OLLAMA_ENDPOINT,
        json=payload,
        timeout=timeout_seconds
    )
    response.raise_for_status()

    result_json: Dict[str, Any] = response.json()
    return result_json.get("response", "").strip()



def clean_and_sanitize_sql(sql_raw: str) -> str:
    """
    Strips markdown formatting, whitespace, trailing semicolons, and automatically
    appends a DEFAULT_SQL_LIMIT if no LIMIT clause is present in the generated SQL query.

    Args:
        sql_raw (str): Raw string output from LLM.

    Returns:
        str: Cleaned and sanitized executable SQL query string.
    """
    # Remove markdown code blocks (e.g., ```sql ... ``` or ``` ...)
    cleaned_sql: str = re.sub(r"```(?:sql)?", "", sql_raw, flags=re.IGNORECASE)
    cleaned_sql = cleaned_sql.replace("```", "").strip()

    # Remove trailing semicolons
    cleaned_sql = cleaned_sql.rstrip(";").strip()

    # Append DEFAULT_SQL_LIMIT to SELECT queries if no LIMIT clause is present
    if cleaned_sql.strip().upper().startswith("SELECT") or cleaned_sql.strip().upper().startswith("WITH"):
        if not re.search(r"\bLIMIT\b", cleaned_sql, flags=re.IGNORECASE):
            cleaned_sql += f" LIMIT {DEFAULT_SQL_LIMIT}"

    return cleaned_sql



def validate_sql_security(sql_query: str) -> Tuple[bool, str]:
    """
    Validates that the generated SQL query is strictly a read-only SELECT query
    and does not contain dangerous DDL/DML statements or multi-statement injections.

    Args:
        sql_query (str): Cleaned SQL query string.

    Returns:
        Tuple[bool, str]: (is_valid, error_reason)
    """
    query_upper: str = sql_query.strip().upper()

    # Must start with SELECT or WITH (CTE)
    if not (query_upper.startswith("SELECT") or query_upper.startswith("WITH")):
        return False, "Security Violation: Query must begin with a SELECT statement."

    # Prohibit dangerous SQL manipulation keywords
    forbidden_keywords: List[str] = [
        "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE",
        "CREATE", "GRANT", "REVOKE", "REPLACE", "EXEC", "EXECUTE",
        "INFORMATION_SCHEMA", "MYSQL.", "PERFORMANCE_SCHEMA"
    ]

    for keyword in forbidden_keywords:
        # Match whole word to avoid accidental substring hits
        pattern: str = r"\b" + keyword + r"\b"
        if re.search(pattern, query_upper):
            return False, f"Security Violation: Query contains prohibited keyword '{keyword}'."

    # Prohibit multiple SQL statements (semicolon in middle of query)
    if ";" in sql_query:
        return False, "Security Violation: Multiple SQL statements are not allowed."

    return True, ""


def execute_safe_query(sql_query: str) -> List[Dict[str, Any]]:
    """
    Executes the validated SQL query against MySQL and returns the results as a list of dicts.

    Args:
        sql_query (str): Validated SQL SELECT query.

    Returns:
        List[Dict[str, Any]]: List of dictionary rows.
    """
    with db.engine.connect() as conn:
        result = conn.execute(text(sql_query))
        rows = result.fetchall()
        # Convert SQLAlchemy Row objects to dictionaries
        return [dict(row._mapping) for row in rows]


def generate_natural_language_response(user_question: str, sql_query: str, query_results: List[Dict[str, Any]]) -> str:
    """
    Sends the database execution results back to Ollama to format a helpful natural language summary.

    Args:
        user_question (str): Original user prompt.
        sql_query (str): The SQL query that was executed.
        query_results (List[Dict[str, Any]]): Data retrieved from the database.

    Returns:
        str: Executive natural language response formatted with Markdown.
    """
    system_prompt: str = (
        "You are an executive ERP assistant.\n"
        "Your goal is to present database results to business managers clearly, professionally, and formatted with Markdown.\n\n"
        "STRICT FORMATTING RULES:\n"
        "1. SINGLE VALUES / TOTALS: Give a direct, concise 1-sentence answer (e.g., 'There are currently 208 active employees in the company.').\n"
        "2. MULTIPLE RECORDS / LISTS: ALWAYS render the data as a clean Markdown table with clear column headers (e.g., | Product Name | SKU Code | Stock Qty | Price |).\n"
        "3. EXECUTIVE SUMMARY: Include a short 1-sentence summary above or below the table (e.g., 'Here is the current inventory breakdown for finished goods:').\n"
        "4. NO TECHNICAL JARGON: Do NOT mention SQL, table names, queries, database IDs, or code execution steps.\n"
        "5. CONCISE COLUMNS: Select only the most meaningful business columns for tables (e.g., product_name, sku_code, stock_qty) rather than raw internal IDs."
    )

    prompt: str = f"""
User Question: "{user_question}"
Data Result: {query_results}

Answer:
"""
    try:
        return call_ollama(prompt, system_prompt=system_prompt, timeout_seconds=15)
    except Exception:
        # Fallback summary formatted as Markdown table if LLM formatting call fails or times out
        if not query_results:
            return "No matching records were found in the database."

        if len(query_results) == 1 and len(query_results[0]) == 1:
            val = list(query_results[0].values())[0]
            return f"The total result for your request is **{val}**."

        keys = list(query_results[0].keys())
        headers = [k.replace('_', ' ').title() for k in keys]
        lines = [
            f"Here is the summary report matching your request ({len(query_results)} records found):",
            "",
            "| " + " | ".join(headers) + " |",
            "| " + " | ".join(["---"] * len(keys)) + " |"
        ]
        for row in query_results:
            row_vals = [str(row.get(k, "") if row.get(k) is not None else "") for k in keys]
            lines.append("| " + " | ".join(row_vals) + " |")

        return "\n".join(lines)





@ai_chat_blueprint.route("/ai-chat", methods=["POST"])
def ai_chat():
    """
    POST /api/ai-chat
    Receives JSON body: { "prompt": "User question here" }
    Returns standardized JSON response schema:
    {
      "errFlag": false,
      "message": "Query processed successfully",
      "answer": "Natural language summary",
      "sql": "SELECT ...",
      "data": [...]
    }
    """
    try:
        json_data: Dict[str, Any] = request.get_json(silent=True) or {}
        user_prompt: str = json_data.get("prompt", "").strip()

        if not user_prompt:
            return jsonify({
                "errFlag": True,
                "message": "Invalid request: 'prompt' field is required in JSON body.",
                "answer": None,
                "sql": None,
                "data": []
            }), 400

        # Step A: Convert natural language prompt to SQL via Ollama
        try:
            raw_sql_response: str = call_ollama(user_prompt, system_prompt=SYSTEM_PROMPT_SQL_GEN)
        except requests.exceptions.RequestException as req_err:
            return jsonify({
                "errFlag": True,
                "message": f"Remote LLM connection error: {str(req_err)}",
                "answer": None,
                "sql": None,
                "data": []
            }), 502

        # Step B: Clean, sanitize, and validate SQL security
        cleaned_sql: str = clean_and_sanitize_sql(raw_sql_response)
        is_valid, security_error = validate_sql_security(cleaned_sql)

        if not is_valid:
            return jsonify({
                "errFlag": True,
                "message": f"Generated query failed security check: {security_error}",
                "answer": None,
                "sql": cleaned_sql,
                "data": []
            }), 400

        # Execute validated SELECT query against MySQL
        try:
            db_results: List[Dict[str, Any]] = execute_safe_query(cleaned_sql)
        except Exception as db_err:
            # Deliver friendly executive chat response instead of breaking UI with raw SQL stack traces
            friendly_err_msg = (
                "I apologize, but I couldn't process that query against the current database structure. "
                "The database tables were recently reset for the Coffee ERP transition. "
                "Please try asking specific questions like **'Show finished goods inventory'** or **'List active employees'**."
            )
            return jsonify({
                "errFlag": False,
                "message": f"Query execution error: {str(db_err)}",
                "answer": friendly_err_msg,
                "sql": cleaned_sql,
                "data": []
            }), 200


        # Step C: Format results into natural language answer via Ollama
        natural_answer: str = generate_natural_language_response(user_prompt, cleaned_sql, db_results)

        return jsonify({
            "errFlag": False,
            "message": "Query processed successfully",
            "answer": natural_answer,
            "sql": cleaned_sql,
            "data": db_results
        }), 200

    except Exception as general_err:
        return jsonify({
            "errFlag": True,
            "message": f"An unexpected error occurred: {str(general_err)}",
            "answer": None,
            "sql": None,
            "data": []
        }), 500
