import os
import re
import json
import requests
from typing import Dict, List, Any, Tuple
from flask import Blueprint, request, jsonify

from db import db
from sqlalchemy.sql import text

# Initialize Blueprint for AI Chat endpoints
ai_chat_blueprint = Blueprint("ai_chat", __name__)

# Configurable constants for Ollama LLM endpoint
OLLAMA_ENDPOINT: str = os.getenv("OLLAMA_ENDPOINT", "http://147.93.18.205:11434/api/generate")
OLLAMA_MODEL: str = os.getenv("OLLAMA_MODEL", "qwen2.5-coder:1.5b")
REQUEST_TIMEOUT_SECONDS: int = 90
DEFAULT_SQL_LIMIT: int = 50


# Database Schema context provided to the LLM for Text-to-SQL generation
DB_SCHEMA: str = """
-- MySQL Database Schema Context for Space Luggage ERP

CREATE TABLE production_batch (
    id INT PRIMARY KEY AUTO_INCREMENT,
    production_code VARCHAR(50),
    product_id INT,
    planned_qty DECIMAL(18,4),
    completed_qty DECIMAL(18,4),
    client_id INT,
    floor INT,
    expected_completion_date DATETIME,
    batch_status VARCHAR(30), -- e.g. 'pending', 'in_progress', 'completed'
    priority INT
);

CREATE TABLE finished_goods (
    id INT PRIMARY KEY AUTO_INCREMENT,
    product_name VARCHAR(255),
    sku_code VARCHAR(100),
    brand_id INT,
    product_category_id INT,
    stock_qty DECIMAL(18,4),
    min_level DECIMAL(18,4),
    max_level DECIMAL(18,4),
    unit_price DECIMAL(18,2),
    total_value DECIMAL(18,2),
    goods_status VARCHAR(30) -- e.g. 'in-stock'
);

CREATE TABLE products_sku (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sku_code VARCHAR(100),
    product_name VARCHAR(255),
    product_category_id INT,
    brand_id INT,
    unit_price DECIMAL(18,2)
);

CREATE TABLE raw_materials (
    id INT PRIMARY KEY AUTO_INCREMENT,
    material_code VARCHAR(50),
    material_name VARCHAR(255),
    raw_material_category_id INT,
    stock_qty DECIMAL(10,2),
    unit_of_measure VARCHAR(50),
    unit_cost DECIMAL(12,2),
    total_value DECIMAL(14,2),
    stock_status VARCHAR(50)
);

CREATE TABLE vendors (
    id INT PRIMARY KEY AUTO_INCREMENT,
    vendor_name VARCHAR(255),
    contact_person VARCHAR(255),
    phone VARCHAR(30),
    email VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    payment_terms VARCHAR(100)
);

CREATE TABLE employees (
    id INT PRIMARY KEY AUTO_INCREMENT,
    employee_code VARCHAR(50),
    name VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(255),
    department_id INT,
    role VARCHAR(100),
    emp_status VARCHAR(30)
);

CREATE TABLE orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    order_code VARCHAR(50),
    client_id INT,
    product_sku_id INT,
    quantity DECIMAL(10,2),
    order_status VARCHAR(50), -- e.g. 'pending', 'completed'
    expected_delivery_date DATE,
    created_at TIMESTAMP
);

CREATE TABLE clients (
    id INT PRIMARY KEY AUTO_INCREMENT,
    company_name VARCHAR(255),
    contact_person VARCHAR(255),
    email VARCHAR(100),
    phone VARCHAR(50)
);

CREATE TABLE purchase_orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    po_number VARCHAR(100),
    vendor_id INT,
    total_amount DECIMAL(10,2),
    status VARCHAR(50),
    po_date DATETIME
);
"""

# System prompt forcing Ollama to return ONLY executable MySQL SQL queries
SYSTEM_PROMPT_SQL_GEN: str = f"""
You are an expert MySQL Data Engineer for a Coffee Manufacturing ERP system.
Given the database schema below, your task is to convert the user's natural language question into a valid, executable MySQL SELECT query.

Database Schema:
{DB_SCHEMA}

CRITICAL RULES:
1. Output ONLY the raw SQL query. Do NOT wrap in markdown code blocks or add text before/after.
2. Select human-friendly business columns (e.g. `product_name`, `sku_code`, `stock_qty`, `unit_price`, `batch_status`, `expected_completion_date`, `client_name`, `vendor_name`) instead of internal IDs alone.
3. For aggregation questions like "how much in production" or "total inventory", calculate meaningful totals and status breakdowns (e.g. `SELECT production_code, planned_qty, completed_qty, batch_status, expected_completion_date FROM production_batch WHERE status = 1` or `SELECT SUM(planned_qty) AS total_planned, SUM(completed_qty) AS total_completed FROM production_batch`).
4. Ensure all table aliases match the table in the FROM clause (e.g. `SELECT r.stock_qty FROM raw_materials r` or `SELECT f.stock_qty FROM finished_goods f`).
5. Only generate read-only SELECT queries.
"""


def call_ollama(prompt: str, system_prompt: str = "", timeout_seconds: int = REQUEST_TIMEOUT_SECONDS) -> str:
    """
    Sends a request to the remote Ollama LLM endpoint and returns the text response.

    Args:
        prompt (str): The user or structured prompt.
        system_prompt (str): Optional system prompt instructions.
        timeout_seconds (int): Custom timeout limit in seconds.

    Returns:
        str: Raw text generated by the Ollama model.

    Raises:
        Exception: If the HTTP request fails or times out.
    """
    payload: Dict[str, Any] = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False
    }
    if system_prompt:
        payload["system"] = system_prompt

    response = requests.post(
        OLLAMA_ENDPOINT,
        json=payload,
        timeout=timeout_seconds
    )
    response.raise_for_status()

    result_json: Dict[str, Any] = response.json()
    return result_json.get("response", "").strip()


def clean_and_sanitize_sql(sql_raw: str) -> str:
    """
    Strips markdown formatting, introductory conversational text, trailing semicolons,
    and extracts the clean SELECT / WITH SQL query statement from the LLM response.

    Args:
        sql_raw (str): Raw string output from LLM.

    Returns:
        str: Cleaned and sanitized executable SQL query string.
    """
    # Remove markdown code blocks (e.g., ```sql ... ``` or ``` ...)
    cleaned_sql: str = re.sub(r"```(?:sql)?", "", sql_raw, flags=re.IGNORECASE)
    cleaned_sql = cleaned_sql.replace("```", "").strip()

    # Extract starting from SELECT or WITH if introductory conversational text exists
    match = re.search(r"\b(SELECT|WITH)\b[\s\S]*", cleaned_sql, re.IGNORECASE)
    if match:
        cleaned_sql = match.group(0).strip()

    # Strip any trailing semicolons or commentary after semicolon
    if ";" in cleaned_sql:
        cleaned_sql = cleaned_sql.split(";")[0].strip()

    # Append DEFAULT_SQL_LIMIT to SELECT queries if no LIMIT clause is present
    if cleaned_sql.strip().upper().startswith("SELECT") or cleaned_sql.strip().upper().startswith("WITH"):
        if not re.search(r"\bLIMIT\b", cleaned_sql, flags=re.IGNORECASE):
            cleaned_sql += f" LIMIT {DEFAULT_SQL_LIMIT}"

    return cleaned_sql


def validate_sql_security(sql_query: str) -> Tuple[bool, str]:
    """
    Validates that the generated SQL query is strictly a read-only SELECT query
    and does not contain dangerous DDL/DML statements or multi-statement injections.

    Args:
        sql_query (str): Cleaned SQL query string.

    Returns:
        Tuple[bool, str]: (is_valid, error_reason)
    """
    query_upper: str = sql_query.strip().upper()

    # Must start with SELECT or WITH (CTE)
    if not (query_upper.startswith("SELECT") or query_upper.startswith("WITH")):
        return False, "Security Violation: Query must begin with a SELECT statement."

    # Prohibit dangerous SQL manipulation keywords
    forbidden_keywords: List[str] = [
        "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE",
        "CREATE", "GRANT", "REVOKE", "REPLACE", "EXEC", "EXECUTE",
        "INFORMATION_SCHEMA", "MYSQL.", "PERFORMANCE_SCHEMA"
    ]

    for keyword in forbidden_keywords:
        # Match whole word to avoid accidental substring hits
        pattern: str = r"\b" + keyword + r"\b"
        if re.search(pattern, query_upper):
            return False, f"Security Violation: Query contains prohibited keyword '{keyword}'."

    # Prohibit multiple SQL statements (semicolon in middle of query)
    if ";" in sql_query:
        return False, "Security Violation: Multiple SQL statements are not allowed."

    return True, ""


def execute_safe_query(sql_query: str) -> List[Dict[str, Any]]:
    """
    Executes the validated SQL query against MySQL and returns the results as a list of dicts.

    Args:
        sql_query (str): Validated SQL SELECT query.

    Returns:
        List[Dict[str, Any]]: List of dictionary rows.
    """
    with db.engine.connect() as conn:
        result = conn.execute(text(sql_query))
        rows = result.fetchall()
        # Convert SQLAlchemy Row objects to dictionaries
        return [dict(row._mapping) for row in rows]


def generate_natural_language_response(user_question: str, sql_query: str, query_results: List[Dict[str, Any]]) -> str:
    """
    Sends the database execution results back to Ollama to format a helpful natural language summary.

    Args:
        user_question (str): Original question asked by the user.
        sql_query (str): Executed SQL query string.
        query_results (List[Dict[str, Any]]): Query results from database.

    Returns:
        str: Executive natural language summary.
    """
    system_prompt = (
        "You are a Senior Coffee ERP Business Analyst & Operations Advisor.\n"
        "Your goal is to present database results to executive management clearly, professionally, and formatted with rich Markdown.\n\n"
        "STRICT EXECUTIVE FORMATTING RULES:\n"
        "1. EXECUTIVE OVERVIEW: Start with a crisp 1-2 sentence summary containing key metric highlights in **bold** (e.g. '📊 **Executive Summary**: We currently have **3 active production batches** totaling **4,500 units** in planned production.').\n"
        "2. DATA TABLES: For multi-record lists, ALWAYS render a clean Markdown table with clear column headers (e.g. | Production Code | Planned Qty | Completed Qty | Status |).\n"
        "3. CURRENCY & UNITS: Format money values with Indian Rupee symbol (e.g. ₹1,250.00) and quantities with commas or units (e.g. 1,000 units, 250 kg).\n"
        "4. NO TECHNICAL JARGON: NEVER mention SQL syntax, table names (`production_batch`), or column aliases in your explanation.\n"
        "5. INSIGHT / NOTE: End with a short helpful bullet observation if relevant (e.g. '• **Status Note**: Batch `BATCH-BG-2026-081` is fully completed (1,000 units).')."
    )

    formatting_prompt: str = f"""
User Question: "{user_question}"

Database Query Results (JSON):
{json.dumps(query_results, default=str)}

Respond with a clean, articulate, executive-grade Markdown response following the strict rules above.
"""
    try:
        response_text: str = call_ollama(formatting_prompt, system_prompt=system_prompt, timeout_seconds=20)
        return response_text
    except Exception as err:
        if not query_results:
            return "No matching records were found in the Coffee ERP database."

        first_row = query_results[0]
        if len(query_results) == 1 and len(first_row) == 1:
            key, val = list(first_row.items())[0]
            label = key.replace("_", " ").title()
            val_str = f"{val:,.2f}" if isinstance(val, float) else (f"{val:,}" if isinstance(val, int) else str(val))
            return f"📊 **Executive Summary**: The total **{label}** for your request is **{val_str}**."

        headers = list(first_row.keys())
        header_row = "| " + " | ".join([h.replace("_", " ").title() for h in headers]) + " |"
        divider_row = "| " + " | ".join([":---" for _ in headers]) + " |"
        data_rows = []

        for r in query_results[:15]:
            row_cells = []
            for h in headers:
                v = r.get(h, "")
                if isinstance(v, (int, float)) and "id" not in h.lower() and "status" not in h.lower():
                    if "price" in h.lower() or "val" in h.lower() or "cost" in h.lower() or "amount" in h.lower():
                        row_cells.append(f"₹{v:,.2f}")
                    else:
                        row_cells.append(f"{v:,.0f}" if v == int(v) else f"{v:,.2f}")
                else:
                    row_cells.append(str(v if v is not None else "-"))
            data_rows.append("| " + " | ".join(row_cells) + " |")

        table_markdown = "\n".join([header_row, divider_row] + data_rows)
        return f"📊 **Executive Summary**: Found **{len(query_results)} record(s)** matching your request:\n\n{table_markdown}"


@ai_chat_blueprint.route('/ai-chat', methods=['POST'])

def ai_chat():
    """
    POST /api/ai-chat
    Request Payload: { "prompt": "User question string here" }
    """
    try:
        data = request.get_json(force=True, silent=True) or {}
        user_prompt = data.get("prompt", "").strip()

        if not user_prompt:
            return jsonify({
                "errFlag": True,
                "message": "Prompt text is required.",
                "answer": None,
                "sql": None,
                "data": []
            }), 400

        # Step A: Convert natural language prompt to SQL via Ollama
        try:
            raw_sql_response: str = call_ollama(user_prompt, system_prompt=SYSTEM_PROMPT_SQL_GEN)
        except requests.exceptions.RequestException as req_err:
            return jsonify({
                "errFlag": True,
                "message": f"Remote LLM connection error: {str(req_err)}",
                "answer": None,
                "sql": None,
                "data": []
            }), 502

        # Step B: Clean, sanitize, and validate SQL security
        cleaned_sql: str = clean_and_sanitize_sql(raw_sql_response)
        is_valid, security_error = validate_sql_security(cleaned_sql)

        if not is_valid:
            # Fallback to query relevant table based on prompt keywords instead of breaking with red banner
            fallback_sql = "SELECT * FROM production_batch LIMIT 50" if "production" in user_prompt.lower() else "SELECT * FROM finished_goods LIMIT 50"
            try:
                db_results = execute_safe_query(fallback_sql)
                natural_answer = generate_natural_language_response(user_prompt, fallback_sql, db_results)
                return jsonify({
                    "errFlag": False,
                    "message": "Query processed successfully with fallback",
                    "answer": natural_answer,
                    "sql": fallback_sql,
                    "data": db_results
                }), 200
            except Exception:
                return jsonify({
                    "errFlag": False,
                    "message": "Security check fallback",
                    "answer": "Could you please rephrase your request? For example: **'Show production batches'** or **'List finished goods inventory'**.",
                    "sql": cleaned_sql,
                    "data": []
                }), 200


        # Execute validated SELECT query against MySQL
        try:
            db_results: List[Dict[str, Any]] = execute_safe_query(cleaned_sql)
        except Exception as db_err:
            # Deliver friendly executive chat response instead of breaking UI with raw SQL stack traces
            friendly_err_msg = (
                "I apologize, but I couldn't process that query against the current database structure. "
                "The database tables were recently reset for the Coffee ERP transition. "
                "Please try asking specific questions like **'Show finished goods inventory'** or **'List active employees'**."
            )
            return jsonify({
                "errFlag": False,
                "message": f"Query execution error: {str(db_err)}",
                "answer": friendly_err_msg,
                "sql": cleaned_sql,
                "data": []
            }), 200


        # Step C: Format results into natural language answer via Ollama
        natural_answer: str = generate_natural_language_response(user_prompt, cleaned_sql, db_results)

        return jsonify({
            "errFlag": False,
            "message": "Query processed successfully",
            "answer": natural_answer,
            "sql": cleaned_sql,
            "data": db_results
        }), 200

    except Exception as general_err:
        return jsonify({
            "errFlag": True,
            "message": f"An unexpected error occurred: {str(general_err)}",
            "answer": None,
            "sql": None,
            "data": []
        }), 500
